#! /usr/bin/python3
from datetime import datetime
import sys

if len(sys.argv) != 2:
    print("Usage: eta <date>")
    print("\nDate format: MM-DD-YY or MM/DD/YY")
    sys.exit(1)

arg = sys.argv[1]

fmts = ["%m-%d-%y", "%m-%d-%Y", "%m-%d-%y", "%m-%d-%Y", "%Y-%m-%d", "%Y%m%d"]
for fmt_str in fmts:
    try:
        date = datetime.strptime(arg, fmt_str).date()
        today = datetime.today().date()
        print("{} day(s) until {}".format((date-today).days, date))
        break
    except:
        pass
else:
    print("Invalid date format: must be MM-DD-YY or MM/DD/YY")
    sys.exit(1)
