#! /usr/bin/python3
from datetime import datetime
import sys

if len(sys.argv) != 2:
    print("Usage: eta <date>")
    print("\nDate format: MM-DD-YY or MM/DD/YY")
    sys.exit(1)

try:
    user_date = sys.argv[1]
    fmt_str = "%m-%d-%y" if '-' in user_date else "%m/%d/%y"
    date = datetime.strptime(user_date, fmt_str).date()
    today = datetime.today().date()
    print("{} day(s) until {}".format((date-today).days, sys.argv[1]))
except:
    print("Invalid date format: must be MM-DD-YY or MM/DD/YY")
    sys.exit(1)
