#! /usr/bin/env python

import os
import sys
from hurry.filesize import size, alternative


cwd = os.getcwd()
arguments = sys.argv[1:]
if len(arguments) == 0:
    arguments.append('.')

for arg in arguments:
    current_arg = os.path.join(cwd, arg)
    if (os.path.isdir(current_arg)):
        folder_size = 0
        for (path, dirs, files) in os.walk(current_arg):
              for f in files:
                  filename = os.path.join(path, f)
                  if os.path.isfile(filename):
                      folder_size += os.path.getsize(filename)
        print str(size(folder_size, system=alternative)) + "\t" + arg

    else:
        file_size = size(os.path.getsize(current_arg), system=alternative)
        print str(file_size) + "\t" + arg
